# Generated by Django 2.2.9 on 2020-01-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('introduce', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='flower/images')),
            ],
        ),
    ]
