# Generated by Django 2.2.9 on 2020-01-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_flowewrpic_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowewrpic',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Flower'),
        ),
    ]
